name: Hello World Workflow

on: 
    push:
        branches:
            - master

jobs:
    say-hello:
        runs-on:  ubuntu-latest
        steps:
            - name: Checkout repository
              run: actions/checkout@v3
            - name: Print the current date
              run: date
            - name: List files in the workspace
              run: ls -la
            - name: View Calender
              run: echo $(date +%B)
